application: shitzen-cn
version: 1
runtime: python
api_version: 1

handlers:
- url: /static/css
  static_dir: static/css

- url: /staticpage
  static_dir: static/pages
  
- url: /static/audio
  static_dir: static/audio
  
- url: /static/js
  static_dir: static/js
  
- url: /static/images
  static_dir: static/images

- url: /static
  static_dir: static

- url: /datastore_admin
  script: $PYTHON_LIB/google/appengine/ext/datastore_admin/main.py
  
- url: /.*
  script: server.py
