application: nich02as 
version: 1
runtime: python
api_version: 1

handlers:
- url: /static/css
  static_dir: static/stylesheets

- url: /staticpage
  static_dir: static/pages

- url: /.*
  script: server.py
